version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 15.0.0
  - dependency-name: tap
    versions:
    - 15.0.0
    - 15.0.1
    - 15.0.2
    - 15.0.3
    - 15.0.4
  - dependency-name: marko
    versions:
    - 5.1.10
    - 5.1.11
    - 5.1.15
    - 5.1.16
    - 5.1.17
    - 5.1.18
    - 5.1.20
    - 5.1.5
    - 5.1.6
    - 5.1.7
    - 5.1.9
    - 5.2.2
    - 5.2.3
    - 5.3.0
    - 5.5.1
    - 5.5.2
    - 5.5.4
    - 5.6.0
    - 5.6.2
    - 5.7.0
    - 5.8.3
    - 5.8.4
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
